import React from 'react';
import {
  LayoutGrid,
  ShoppingCart,
  Users,
  PieChart,
  Search,
  Bell,
  HelpCircle,
  Plus,
  ChevronDown,
  Calendar,
  CheckCircle,
  Building2,
  Eye,
  Download,
  Hourglass,
  Send,
  ArrowUpRight,
  ArrowDownRight,
  MoreHorizontal,
  Sun,
  Moon,
  Menu,
  X,
  List,
  Grid,
  Filter,
  Trash2,
  MoreVertical,
  ChevronLeft,
  ChevronRight,
  Edit2,
  Shield,
  Lock,
  Mail,
  UserPlus,
  Ban,
  CheckSquare,
  Square,
  ArrowUpDown,
  ArrowUp,
  ArrowDown,
  XCircle,
  ArrowLeft,
  FileText,
  CreditCard,
  Share2,
  Clock,
  Settings,
  User,
  TrendingUp,
  AlertCircle,
  Briefcase,
  Scale,
  Gavel,
  BarChart3
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutGrid,
  Sales: ShoppingCart,
  Users: Users,
  Reports: PieChart,
  Search: Search,
  Notification: Bell,
  Help: HelpCircle,
  Plus: Plus,
  ChevronDown: ChevronDown,
  Calendar: Calendar,
  CheckCircle: CheckCircle,
  Business: Building2,
  View: Eye,
  Download: Download,
  Pending: Hourglass,
  Send: Send,
  ArrowUp: ArrowUp,
  ArrowDown: ArrowDown,
  ArrowUpRight: ArrowUpRight,
  ArrowDownRight: ArrowDownRight,
  More: MoreHorizontal,
  Sun: Sun,
  Moon: Moon,
  Menu: Menu,
  X: X,
  List: List,
  Grid: Grid,
  Filter: Filter,
  Trash: Trash2,
  MoreVertical: MoreVertical,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  Edit: Edit2,
  Shield: Shield,
  Lock: Lock,
  Mail: Mail,
  UserPlus: UserPlus,
  Ban: Ban,
  CheckSquare: CheckSquare,
  Square: Square,
  Sort: ArrowUpDown,
  Clear: XCircle,
  ArrowLeft: ArrowLeft,
  FileText: FileText,
  CreditCard: CreditCard,
  Share: Share2,
  Clock: Clock,
  Settings: Settings,
  User: User,
  TrendingUp: TrendingUp,
  AlertCircle: AlertCircle,
  Briefcase: Briefcase,
  Scale: Scale,
  Gavel: Gavel,
  BarChart: BarChart3
};

export type IconName = keyof typeof Icons;